### ISSUE TITLE
Issue with Centering Content within RippleAnimation

### ISSUE THREAD

**Issue by bbottema** [AwabSabir373/awesome_ripple_animation#2]
I've been debugging my issue with GPT-4 for a few hours now and we came to the conclusion that your library contains a bug here that we can't work around in a reliable way that will work on all devices.

Here's its bug report. I hope it's useful to you.

---
I am writing to inform you about an issue I have encountered when using the awesome_ripple_animation package in my Flutter application. I have found it difficult to center content within the RippleAnimation widget, especially when using it within a dialog.

From my investigation, the root cause seems to stem from how CustomPaint (and thus the AnimatedCircle) sizes itself within the RippleAnimation widget. It appears that CustomPaint tries to expand to fill all the available space it can get, and it does not respect the size of the content being painted. As a result, the content within the RippleAnimation widget tends to align to the top left corner instead of being centered.

I noticed that in the RippleAnimation class, a Scaffold is used which doesn't have a predefined size. This may further contribute to the problem as the Scaffold allows the CustomPaint to expand as much as it can, hence affecting the positioning of the content.

I believe that other users of your package may encounter this issue as well, especially those who wish to center content within a RippleAnimation. Therefore, I'd like to suggest a potential feature improvement:

Enable the RippleAnimation and the underlying CustomPaint/AnimatedCircle to respect the size of the content being painted. This could involve adjusting the sizing logic within RippleAnimation and AnimatedCircle to make sure the size of the painted content is considered during layout calculation.
Doing this would greatly increase the flexibility and ease-of-use of your package. Users would be able to place a RippleAnimation widget anywhere in their layout, with the confidence that it will be properly positioned relative to its container.

Thank you for your attention and for the excellent package. I am looking forward to any updates that address this issue.

Best Regards,

**Comment by bbottema** [comment]
With the PR, the content can be centered properly again, like any other widget:

Example usage:
```dart
return Dialog(
      child: Center(
        child: RippleAnimation(
          repeat: true,
          color: Colors.purpleAccent,
          minRadius: 60,
          ripplesCount: 10,
          size: Size(50, 50), // the size of the content (microphone icon)
          child: Image.asset(
            'assets/images/microphone.png',
          ),
        ),
      ),
    );
```

**Comment by AwabSabir373** [comment]
Well my dependency too much old when i created that time there is no any
support available
